# Generated by Django 5.2.3 on 2025-07-01 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageFeatures',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('image_hash', models.CharField(max_length=64, unique=True)),
                ('image_name', models.CharField(max_length=255)),
                ('features', models.JSONField()),
            ],
        ),
    ]
